# POST http://localhost:3000/api/cursos/programacion
# PUT http://localhost:3000/api/cursos/programacion
# DELETE http://localhost:3000/api/cursos/programacion
# OPTIONS http://localhost:3000/
TRACE http://localhost:3000/